<?php


return [
    
    'CentralDashboardControllers@Dashboard' => 'general',
    'CentralDashboardControllers@changeLang' => 'general',
    'CentralDashboardControllers@changeTheme' => 'general',
    'CentralDashboardControllers@changeThemeToDefault' => 'general',
 
    
    'UsersControllers@index' => 'list-users',
    'UsersControllers@edit' => 'edit-user',
    'UsersControllers@update' => 'edit-user',
    'UsersControllers@fastEdit' => 'edit-user',
    'UsersControllers@add' => 'add-user',
    'UsersControllers@create' => 'add-user',
    'UsersControllers@delete' => 'delete-user',
    'UsersControllers@uploadImage' => 'uploadImage-user',
    'UsersControllers@deleteImage' => 'deleteImage-user',

    'GroupsControllers@index' => 'list-groups',
    'GroupsControllers@edit' => 'edit-group',
    'GroupsControllers@update' => 'edit-group',
    'GroupsControllers@fastEdit' => 'edit-group',
    'GroupsControllers@add' => 'add-group',
    'GroupsControllers@create' => 'add-group',
    'GroupsControllers@delete' => 'delete-group',

    'NotificationTemplateControllers@index' => 'list-notificationTemplates',
    'NotificationTemplateControllers@index@edit' => 'edit-notificationTemplate',
    'NotificationTemplateControllers@update' => 'edit-notificationTemplate',
    'NotificationTemplateControllers@fastEdit' => 'edit-notificationTemplate',
    'NotificationTemplateControllers@delete' => 'delete-notificationTemplate',

    'MembershipControllers@index' => 'list-memberships',
    'MembershipControllers@edit' => 'edit-membership',
    'MembershipControllers@update' => 'edit-membership',
    'MembershipControllers@fastEdit' => 'edit-membership',
    'MembershipControllers@add' => 'add-membership',
    'MembershipControllers@create' => 'add-membership',
    'MembershipControllers@delete' => 'delete-membership',

    'FeatureControllers@index' => 'list-features',
    'FeatureControllers@edit' => 'edit-feature',
    'FeatureControllers@update' => 'edit-feature',
    'FeatureControllers@fastEdit' => 'edit-feature',
    'FeatureControllers@add' => 'add-feature',
    'FeatureControllers@create' => 'add-feature',
    'FeatureControllers@delete' => 'delete-feature',

    'AddonsControllers@index' => 'list-addons',
    'AddonsControllers@edit' => 'edit-addon',
    'AddonsControllers@update' => 'edit-addon',
    'AddonsControllers@fastEdit' => 'edit-addon',
    'AddonsControllers@add' => 'add-addon',
    'AddonsControllers@create' => 'add-addon',
    'AddonsControllers@delete' => 'delete-addon',

    'CouponControllers@index' => 'list-coupons',
    'CouponControllers@edit' => 'edit-coupon',
    'CouponControllers@update' => 'edit-coupon',
    'CouponControllers@fastEdit' => 'edit-coupon',
    'CouponControllers@add' => 'add-coupon',
    'CouponControllers@create' => 'add-coupon',
    'CouponControllers@delete' => 'delete-coupon',

    'ExtraQuotaControllers@index' => 'list-extraQuotas',
    'ExtraQuotaControllers@edit' => 'edit-extraQuota',
    'ExtraQuotaControllers@update' => 'edit-extraQuota',
    'ExtraQuotaControllers@fastEdit' => 'edit-extraQuota',
    'ExtraQuotaControllers@add' => 'add-extraQuota',
    'ExtraQuotaControllers@create' => 'add-extraQuota',
    'ExtraQuotaControllers@delete' => 'delete-extraQuota',

    'FAQControllers@index' => 'list-faqs',
    'FAQControllers@edit' => 'edit-faq',
    'FAQControllers@update' => 'edit-faq',
    'FAQControllers@fastEdit' => 'edit-faq',
    'FAQControllers@add' => 'add-faq',
    'FAQControllers@create' => 'add-faq',
    'FAQControllers@delete' => 'delete-faq',

    'BankAccountControllers@index' => 'list-bankAccounts',
    'BankAccountControllers@edit' => 'edit-bankAccount',
    'BankAccountControllers@update' => 'edit-bankAccount',
    'BankAccountControllers@fastEdit' => 'edit-bankAccount',
    'BankAccountControllers@add' => 'add-bankAccount',
    'BankAccountControllers@create' => 'add-bankAccount',
    'BankAccountControllers@delete' => 'delete-bankAccount',
    'BankAccountControllers@uploadImage' => 'uploadImage-bankAccount',
    'BankAccountControllers@deleteImage' => 'deleteImage-bankAccount',

    'ChangeLogControllers@index' => 'list-changeLogs',
    'ChangeLogControllers@edit' => 'edit-changeLog',
    'ChangeLogControllers@update' => 'edit-changeLog',
    'ChangeLogControllers@fastEdit' => 'edit-changeLog',
    'ChangeLogControllers@add' => 'add-changeLog',
    'ChangeLogControllers@create' => 'add-changeLog',
    'ChangeLogControllers@delete' => 'delete-changeLog',
    'ChangeLogControllers@uploadImage' => 'uploadImage-changeLog',
    'ChangeLogControllers@deleteImage' => 'deleteImage-changeLog',

    'CentralTicketControllers@index' => 'list-tickets',
    'CentralTicketControllers@edit' => 'edit-ticket',
    'CentralTicketControllers@view' => 'view-ticket',
    'CentralTicketControllers@update' => 'edit-ticket',
    'CentralTicketControllers@fastEdit' => 'edit-ticket',
    'CentralTicketControllers@add' => 'add-ticket',
    'CentralTicketControllers@create' => 'add-ticket',
    'CentralTicketControllers@delete' => 'delete-ticket',
    'CentralTicketControllers@uploadImage' => 'uploadImage-ticket',
    'CentralTicketControllers@deleteImage' => 'deleteImage-ticket',
    'CentralTicketControllers@addComment' => 'addComment-ticket',
    'CentralTicketControllers@updateComment' => 'updateComment-ticket',
    'CentralTicketControllers@deleteComment' => 'deleteComment-ticket',

    'DepartmentControllers@index' => 'list-departments',
    'DepartmentControllers@edit' => 'edit-department',
    'DepartmentControllers@update' => 'edit-department',
    'DepartmentControllers@fastEdit' => 'edit-department',
    'DepartmentControllers@add' => 'add-department',
    'DepartmentControllers@create' => 'add-department',
    'DepartmentControllers@delete' => 'delete-department',

    'ClientControllers@index' => 'list-clients',
    'ClientControllers@view' => 'view-client',
    'ClientControllers@invLogin' => 'invisibleLogin-client',
    'ClientControllers@pinCodeLogin' => 'loginByPinCode-client',
    'ClientControllers@updateSettings' => 'updateChannelSettings-client',
    'ClientControllers@transferDays' => 'transferDays-client',
    'ClientControllers@compensation' => 'compensate-client',
    'ClientControllers@add' => 'add-client',
    'ClientControllers@create' => 'add-client',
    'ClientControllers@delete' => 'delete-client',

    'TransferRequestControllers@index' => 'list-transfers',
    'TransferRequestControllers@edit' => 'view-transfer',
    'TransferRequestControllers@delete' => 'delete-transfer',
    'TransferRequestControllers@update' => 'edit-transfer',
  
    'InvoiceControllers@index' => 'list-invoices',
    'InvoiceControllers@view' => 'view-invoice',
    'InvoiceControllers@downloadPDF' => 'view-invoice',
    'InvoiceControllers@delete' => 'delete-invoice',
    // 'InvoiceControllers@create' => 'add-invoice',
    // 'InvoiceControllers@add' => 'add-invoice',

    'CentralCategoryControllers@index' => 'list-categorys',
    'CentralCategoryControllers@edit' => 'edit-category',
    'CentralCategoryControllers@update' => 'edit-category',
    'CentralCategoryControllers@fastEdit' => 'edit-category',
    'CentralCategoryControllers@add' => 'add-category',
    'CentralCategoryControllers@create' => 'add-category',
    'CentralCategoryControllers@delete' => 'delete-category',

    'PageControllers@index' => 'list-pages',
    'PageControllers@edit' => 'edit-page',
    'PageControllers@update' => 'edit-page',
    'PageControllers@fastEdit' => 'edit-page',
    'PageControllers@add' => 'add-page',
    'PageControllers@create' => 'add-page',
    'PageControllers@delete' => 'delete-page',
    
    'SliderControllers@index' => 'list-sliders',
    'SliderControllers@edit' => 'edit-slider',
    'SliderControllers@update' => 'edit-slider',
    'SliderControllers@fastEdit' => 'edit-slider',
    'SliderControllers@add' => 'add-slider',
    'SliderControllers@create' => 'add-slider',
    'SliderControllers@delete' => 'delete-slider',
    'SliderControllers@uploadImage' => 'uploadImage-slider',
    'SliderControllers@deleteImage' => 'deleteImage-slider',

    'ContactUsControllers@index' => 'list-contactUs',
    'ContactUsControllers@edit' => 'edit-contactUs',
    'ContactUsControllers@fastEdit' => 'edit-contactUs',
    'ContactUsControllers@update' => 'edit-contactUs',
    'ContactUsControllers@reply' => 'reply-contactUs',
    'ContactUsControllers@postReply' => 'reply-contactUs',
    'ContactUsControllers@delete' => 'delete-contactUs',

    'SectionControllers@index' => 'list-sections',
    'SectionControllers@edit' => 'edit-section',
    'SectionControllers@update' => 'edit-section',
    'SectionControllers@fastEdit' => 'edit-section',
    'SectionControllers@add' => 'add-section',
    'SectionControllers@create' => 'add-section',
    'SectionControllers@delete' => 'delete-section',
    'SectionControllers@uploadImage' => 'uploadImage-section',
    'SectionControllers@deleteImage' => 'deleteImage-section',
];
