<?php


return [
    
    'DashboardControllers@Dashboard' => 'general',
    'DashboardControllers@changeLang' => 'general',
    'DashboardControllers@qrIndex' => 'general',
    'DashboardControllers@updateName' => 'general',
    'DashboardControllers@getQR' => 'general',

    'DashboardControllers@faqs' => 'general',
    'DashboardControllers@changeLogs' => 'general',
    'DashboardControllers@helpCenter' => 'general',
    'DashboardControllers@addRate' => 'general',

    'RepliesControllers@index' => 'list-replies',
    'RepliesControllers@edit' => 'edit-reply',
    'RepliesControllers@update' => 'edit-reply',
    'RepliesControllers@fastEdit' => 'edit-reply',
    'RepliesControllers@add' => 'add-reply',
    'RepliesControllers@create' => 'add-reply',
    'RepliesControllers@delete' => 'delete-reply',

    'TemplatesControllers@index' => 'list-templates',
    'TemplatesControllers@edit' => 'edit-template',
    'TemplatesControllers@update' => 'edit-template',
    'TemplatesControllers@fastEdit' => 'edit-template',
    'TemplatesControllers@add' => 'add-template',
    'TemplatesControllers@create' => 'add-template',
    'TemplatesControllers@delete' => 'delete-template',
    
    'UsersControllers@index' => 'list-users',
    'UsersControllers@edit' => 'edit-user',
    'UsersControllers@update' => 'edit-user',
    'UsersControllers@fastEdit' => 'edit-user',
    'UsersControllers@add' => 'add-user',
    'UsersControllers@create' => 'add-user',
    'UsersControllers@delete' => 'delete-user',
    'UsersControllers@uploadImage' => 'uploadImage-user',
    'UsersControllers@deleteImage' => 'deleteImage-user',

    'GroupsControllers@index' => 'list-groups',
    'GroupsControllers@edit' => 'edit-group',
    'GroupsControllers@update' => 'edit-group',
    'GroupsControllers@fastEdit' => 'edit-group',
    'GroupsControllers@add' => 'add-group',
    'GroupsControllers@create' => 'add-group',
    'GroupsControllers@delete' => 'delete-group',

    'GroupNumbersControllers@index' => 'list-group-numbers',
    'GroupNumbersControllers@edit' => 'edit-group-number',
    'GroupNumbersControllers@update' => 'edit-group-number',
    'GroupNumbersControllers@fastEdit' => 'edit-group-number',
    'GroupNumbersControllers@add' => 'add-group-number',
    'GroupNumbersControllers@create' => 'add-group-number',
    'GroupNumbersControllers@delete' => 'delete-group-number',
    'GroupNumbersControllers@addGroupNumbers' =>'add-number-to-group',
    'GroupNumbersControllers@postAddGroupNumbers' =>'add-number-to-group',
    'GroupNumbersControllers@checkFile' =>'add-number-to-group',
    'GroupNumbersControllers@report'  =>  'list-groupNumberReports',
    
    'ApiModsControllers@msgsArchive'  => 'list-messages-archive',
    'ApiModsControllers@index'  =>  'list-statuses',

    'ContactsControllers@index' => 'list-contacts',
    'ContactsControllers@edit' => 'edit-contact',
    'ContactsControllers@update' => 'edit-contact',
    'ContactsControllers@fastEdit' => 'edit-contact',
    'ContactsControllers@add' => 'add-contact',
    'ContactsControllers@create' => 'add-contact',
    'ContactsControllers@delete' => 'delete-contact',
    'ContactsControllers@downloadContacts' => 'export-contacts',

    'ProfileControllers@personalInfo' => 'general',
    'ProfileControllers@updatePersonalInfo' => 'general',
    'ProfileControllers@uploadImage' => 'profile',
    'ProfileControllers@deleteImage' => 'profile',
    'ProfileControllers@postChangePassword' => 'profile',
    'ProfileControllers@postPaymentInfo' => 'paymentInfo',

    'WAAccountController@subscription' => 'subscription',
    'WAAccountController@screenshot' => 'subscription',
    'WAAccountController@syncAll' => 'subscription',
    'WAAccountController@closeConn' => 'subscription',
    'WAAccountController@unBlock' => 'subscription',
    'WAAccountController@read' => 'subscription',
    'WAAccountController@syncDialogs' => 'subscription',
    'WAAccountController@syncContacts' => 'subscription',
    'WAAccountController@syncLabels' => 'subscription',
    'WAAccountController@syncProducts' => 'subscription',
    'WAAccountController@syncCollections' => 'subscription',
    'WAAccountController@syncReplies' => 'subscription',
    'WAAccountController@syncOrders' => 'subscription',
    'WAAccountController@restoreAccountSettings' => 'subscription',
    'WAAccountController@clearMessagesQueue' => 'subscription',

    'TenantInvoiceControllers@index' => 'list-invoices',
    'TenantInvoiceControllers@view' => 'view-invoice',
    'TenantInvoiceControllers@downloadPDF' => 'view-invoice',
    'TenantInvoiceControllers@checkout' => 'pay-invoice',
    'TenantInvoiceControllers@pushInvoice' => 'pay-invoice',
    'TenantInvoiceControllers@postCheckout' => 'general',

    'TicketControllers@index' => 'list-tickets',
    'TicketControllers@edit' => 'edit-ticket',
    'TicketControllers@view' => 'view-ticket',
    'TicketControllers@update' => 'edit-ticket',
    'TicketControllers@fastEdit' => 'edit-ticket',
    'TicketControllers@add' => 'add-ticket',
    'TicketControllers@create' => 'add-ticket',
    'TicketControllers@delete' => 'delete-ticket',
    'TicketControllers@uploadImage' => 'uploadImage-ticket',
    'TicketControllers@deleteImage' => 'deleteImage-ticket',
    'TicketControllers@addComment' => 'addComment-ticket',
    'TicketControllers@removeComment' => 'deleteComment-ticket',

    'UserStorageControllers@index' => 'list-storage',
    'UserStorageControllers@bots' => 'list-storage',
    'UserStorageControllers@groupMsgs' => 'list-storage',
    'UserStorageControllers@chats' => 'list-storage',
    'UserStorageControllers@getByTypeAndId' => 'list-storage',
    'UserStorageControllers@removeByTypeAndId' => 'delete-storage',
    'UserStorageControllers@removeChatFile' => 'delete-storage',


    // Belonged To Addon
    'ApiSettingController@apiSetting' => 'apiSetting',
    'ApiSettingController@apiGuide' => 'apiGuide',
    'ApiSettingController@webhookSetting' => 'webhookSetting',
    'ApiSettingController@postWebhookSetting' => 'webhookSetting',

    'BotControllers@index' => 'list-bots',
    'BotControllers@edit' => 'edit-bot',
    'BotControllers@update' => 'edit-bot',
    'BotControllers@fastEdit' => 'edit-bot',
    'BotControllers@changeStatus' => 'edit-bot',
    'BotControllers@add' => 'add-bot',
    'BotControllers@addBotReply' => 'add-bot',
    'BotControllers@create' => 'add-bot',
    'BotControllers@copy' => 'copy-bot',
    'BotControllers@delete' => 'delete-bot',
    'BotControllers@uploadImage' => 'uploadImage-bot',
    'BotControllers@deleteImage' => 'deleteImage-bot',

    'BotPlusControllers@index' => 'list-bots-plus',
    'BotPlusControllers@edit' => 'edit-bot-plus',
    'BotPlusControllers@update' => 'edit-bot-plus',
    'BotPlusControllers@changeStatus' => 'edit-bot-plus',
    'BotPlusControllers@fastEdit' => 'edit-bot-plus',
    'BotPlusControllers@add' => 'add-bot-plus',
    'BotPlusControllers@create' => 'add-bot-plus',
    'BotPlusControllers@copy' => 'copy-bot-plus',
    'BotPlusControllers@delete' => 'delete-bot-plus',
    'BotPlusControllers@uploadImage' => 'uploadImage-bot-plus',
    'BotPlusControllers@deleteImage' => 'deleteImage-bot-plus',

    'GroupMsgsControllers@index' => 'list-group-messages',
    'GroupMsgsControllers@add' => 'add-group-message' ,
    'GroupMsgsControllers@create' => 'add-group-message',
    'GroupMsgsControllers@resend' => 'add-group-message',
    'GroupMsgsControllers@view' => 'view-group-message',
    'GroupMsgsControllers@charts' => 'charts-group-message',
    'GroupMsgsControllers@uploadImage' => 'uploadImage-group-message',
    
    'ListMsgControllers@index' => 'list-lists',
    'ListMsgControllers@edit' => 'edit-list',
    'ListMsgControllers@update' => 'edit-list',
    'ListMsgControllers@changeStatus' => 'edit-list',
    'ListMsgControllers@fastEdit' => 'edit-list',
    'ListMsgControllers@add' => 'add-list',
    'ListMsgControllers@create' => 'add-list',
    'ListMsgControllers@copy' => 'copy-list',
    'ListMsgControllers@delete' => 'delete-list',

    'PollsControllers@index' => 'list-polls',
    'PollsControllers@edit' => 'edit-poll',
    'PollsControllers@update' => 'edit-poll',
    'PollsControllers@changeStatus' => 'edit-poll',
    'PollsControllers@fastEdit' => 'edit-poll',
    'PollsControllers@add' => 'add-poll',
    'PollsControllers@create' => 'add-poll',
    'PollsControllers@copy' => 'copy-poll',
    'PollsControllers@delete' => 'delete-poll',

    'TemplateMsgControllers@index' => 'list-templates-messages',
    'TemplateMsgControllers@edit' => 'edit-template-message',
    'TemplateMsgControllers@deleteImage' => 'deleteImage-template-message',
    'TemplateMsgControllers@update' => 'edit-template-message',
    'TemplateMsgControllers@changeStatus' => 'edit-template-message',
    'TemplateMsgControllers@fastEdit' => 'edit-template-message',
    'TemplateMsgControllers@add' => 'add-template-message',
    'TemplateMsgControllers@create' => 'add-template-message',
    'TemplateMsgControllers@uploadImage' => 'add-template-message',
    'TemplateMsgControllers@copy' => 'copy-template-message',
    'TemplateMsgControllers@delete' => 'delete-template-message',

    // ********************* Business ************************** //
    'CategoryControllers@index' => 'list-categories',
    'CategoryControllers@edit' => 'edit-category',
    'CategoryControllers@update' => 'edit-category',
    'CategoryControllers@fastEdit' => 'edit-category',
    'CategoryControllers@add' => 'add-category',
    'CategoryControllers@create' => 'add-category',
    'CategoryControllers@delete' => 'delete-category',
    'CategoryControllers@syncLabels' => 'sync-categories',

    'QuickRepliesControllers@index' => 'list-quickReplies',
    'QuickRepliesControllers@edit' => 'edit-quickReply',
    'QuickRepliesControllers@update' => 'edit-quickReply',
    'QuickRepliesControllers@delete' => 'delete-quickReply',

    'WACollectionControllers@index' => 'list-collections',

    'ProductControllers@index' => 'list-products',
    'ProductControllers@edit' => 'edit-product',
    'ProductControllers@update' => 'edit-product',
    'ProductControllers@fastEdit' => 'edit-product',
    'ProductControllers@view' => 'view-product',
    'ProductControllers@add' => 'add-product',
    'ProductControllers@create' => 'add-product',
    'ProductControllers@delete' => 'delete-product',
    'ProductControllers@uploadImage' => 'add-product',
    'ProductControllers@deleteImage' => 'deleteImage-product',

    'OrderControllers@index' => 'list-orders',
    'OrderControllers@view' => 'view-order',


    /************************** In Review ********************/
    'SubscriptionControllers@packages' => 'general',
    'SubscriptionControllers@updateSubscription' => 'general',
    'SubscriptionControllers@postBundle' => 'general',
    'SubscriptionControllers@postUpdateSubscription' => 'general',
    'SubscriptionControllers@updateAddonStatus' => 'general',
    'SubscriptionControllers@updateAddonStatus' => 'general',
    'SubscriptionControllers@sync' => 'general',
    'SubscriptionControllers@postSync' => 'general',
    'SubscriptionControllers@paymentError' => 'general',
    'SubscriptionControllers@checkout' => 'general',
    'SubscriptionControllers@addCoupon' => 'general',
    'SubscriptionControllers@postCheckout' => 'general',
    'SubscriptionControllers@completeOrder' => 'general',
    'SubscriptionControllers@pushInvoice' => 'general',
    'SubscriptionControllers@getCities' => 'general',
    'SubscriptionControllers@bankTransfer' => 'general',
    'SubscriptionControllers@completeJob' => 'general',

    'ProfileControllers@extraQuotas' => 'extraQuotas',
    'ProfileControllers@postExtraQuotas' => 'extraQuotas',
    'ProfileControllers@addons' => 'addons',
    'ProfileControllers@postAddons' => 'addons',
    
];
